
copy: tests/test-install
copyrev: e46f0b9890b7e8819df241571ba181d580a5a74f

hg debuginstall
  $ hg debuginstall
  Checking encoding (ascii)...
  Checking extensions...
  Checking templates...
  Checking patch...
  Checking commit editor...
  Checking username...
  No problems detected

hg debuginstall with no username
  $ HGUSER= hg debuginstall
  Checking encoding (ascii)...
  Checking extensions...
  Checking templates...
  Checking patch...
  Checking commit editor...
  Checking username...
   no username supplied (see "hg help config")
   (specify a username in your .hgrc file)
  1 problems detected, please check your install!

  $ true
